# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('battle_id', models.AutoField(primary_key=True, serialize=False)),
                ('battle_name', models.CharField(max_length=120)),
                ('hashtag1', models.CharField(max_length=250)),
                ('hashtag2', models.CharField(max_length=250)),
                ('battle_start', models.DateTimeField(auto_now_add=True)),
                ('battle_end', models.DateTimeField(default=datetime.datetime(2016, 3, 11, 16, 33, 50, 809374))),
                ('tag1_num_tweets', models.IntegerField(default=0)),
                ('tag2_num_tweets', models.IntegerField(default=0)),
                ('tag1_num_spell_errors', models.IntegerField(default=0)),
                ('tag2_num_spell_errors', models.IntegerField(default=0)),
                ('num_tweet_winner', models.CharField(default='', max_length=250)),
                ('num_spell_winner', models.CharField(default='', max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('crawl_status', models.CharField(choices=[('R', 'Running'), ('D', 'Done')], default='R', max_length=1)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
