# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagbattle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='battle_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 11, 16, 34, 7, 490771)),
        ),
    ]
